### ISSUE TITLE
Use a different base transformers model

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#181]
I see that you are using deberta-v3-large as the base transformers model. I am wondering, for a specific use case (for example, scientific, aerospace, car domain, or any other), do you think it will be better to pre-train from scratch another transformer (for example, electra), since deberta-v3-large doesn't have pre-training code yet?

**Comment by yangheng95** [comment]
As I thought, although there are some differences between different domains, it is reasonable to train from an existing pre-trained model given not enough resources to pretrain a new model, because all the pretrained language models are probably adaptive to different domains.  But if you have enough corpus and GPU, you can try to retrain a new model, but it is resource-intense and expensive.

**Comment by pepi99** [comment]
I would like to do both. What do you mean by corpus?

**Comment by yangheng95** [comment]
I mean it is a large-scale text dataset that can provide enough text for unsupervised MLM pertaining. And pretraining is out of my research.

**Comment by yangheng95** [comment]
For example, the C4 corpus used in pretraining T5.

**Comment by pepi99** [comment]
This is useful. It seems that this question is something that I should think about. Thanks for the help!
