### ISSUE TITLE
Multilingual and English examples not working anymore

### ISSUE THREAD

**Issue by ik4Rus** [yangheng95/PyABSA#41]
Hi, 

Thank you for the great repository. 
For me especially the English models are interesting. Unfortunately your examples *examples/aspect_term_extraction/extract_aspects.py* and *extract_aspects_multilingual.py* do not work for me. 

### Expected behavior
The sample scripts *extract_aspects.py* and *extract_aspects_multilingual.py* can be executed. 

### Actual behavior 
The `get_checkpoint` function doesn't find any model for English.
```python 
[...]
model_path = APCTrainedModelManager.get_checkpoint(checkpoint_name='English')
[...]
## Checkpoint:English is not found.
```
The reason is that there is no English language model in the *checkpoints.json*, that is being downloaded. 

```json
{ "0.8.8.0+":{
    "APC":{
        "chinese":{
        "id": "https://drive.google.com/file/d/12UPwGEOWcBToEmpiKAyeKTmXZ-38LDuo/view?usp=sharing",
        "description": "",
        "comment": ""
        }
    },
    "ATEPC":{
      "chinese":{
        "id": "https://drive.google.com/file/d/1LDCoYEhZLWt0pKsKflC3pOXUV3JMDT64/view?usp=sharing",
        "description": "",
        "comment": ""
      }
    }
}
```
I tried using `download_pretrained_model ` to download an old model, but this one doesn't seem to be compatible anymore:
```python 
download_pretrained_model(task  ='APC', language = 'english', archive_path = '1AE2DC72vigxdAlYKjiV4_IfWsPUH7aX_')
```
It would be great if you could provide an English model for the new version of your package or explain how to run the examples. 

Thank you 🙏
Ingo

**Comment by yangheng95** [comment]
Hi,


Thank you for your report. I will upload new checkpoints in days.


Cheers!



---Original---
From: "Ingo ***@***.***&gt;
Date: Sun, Jul 11, 2021 06:16 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [yangheng95/PyABSA] Multilingual and English examples not working anymore (#41)




 
Hi,
 
Thank you for the great repository.
 For me especially the English models are interesting. Unfortunately your examples examples/aspect_term_extraction/extract_aspects.py and extract_aspects_multilingual.py do not work for me.
 
Expected behavior
 
The sample scripts extract_aspects.py and extract_aspects_multilingual.py can be executed.
 
Actual behavior
 
The get_checkpoint function doesn't find any model for English.
 [...] model_path = APCTrainedModelManager.get_checkpoint(checkpoint_name='English') [...] ## Checkpoint:English is not found.
 
The reason is that there is no English language model in the checkpoints.json, that is being downloaded.
 { "0.8.8.0+":{     "APC":{         "chinese":{         "id": "https://drive.google.com/file/d/12UPwGEOWcBToEmpiKAyeKTmXZ-38LDuo/view?usp=sharing",         "description": "",         "comment": ""         }     },     "ATEPC":{       "chinese":{         "id": "https://drive.google.com/file/d/1LDCoYEhZLWt0pKsKflC3pOXUV3JMDT64/view?usp=sharing",         "description": "",         "comment": ""       }     } }
 
I tried using download_pretrained_model  to download an old model, but this one doesn't seem to be compatible anymore:
 download_pretrained_model(task  ='APC', language = 'english', archive_path = '1AE2DC72vigxdAlYKjiV4_IfWsPUH7aX_')
 
It would be great if you could provide an English model for the new version of your package or explain how to run the examples.
 
Thank you 🙏
 Ingo
 Ingo

**Comment by yangheng95** [comment]
> Hi,
> 
> Thank you for the great repository.
> For me especially the English models are interesting. Unfortunately your examples _examples/aspect_term_extraction/extract_aspects.py_ and _extract_aspects_multilingual.py_ do not work for me.
> 
> ### Expected behavior
> The sample scripts _extract_aspects.py_ and _extract_aspects_multilingual.py_ can be executed.
> 
> ### Actual behavior
> The `get_checkpoint` function doesn't find any model for English.
> 
> ```python
> [...]
> model_path = APCTrainedModelManager.get_checkpoint(checkpoint_name='English')
> [...]
> ## Checkpoint:English is not found.
> ```
> 
> The reason is that there is no English language model in the _checkpoints.json_, that is being downloaded.
> 
> ```json
> { "0.8.8.0+":{
>     "APC":{
>         "chinese":{
>         "id": "https://drive.google.com/file/d/12UPwGEOWcBToEmpiKAyeKTmXZ-38LDuo/view?usp=sharing",
>         "description": "",
>         "comment": ""
>         }
>     },
>     "ATEPC":{
>       "chinese":{
>         "id": "https://drive.google.com/file/d/1LDCoYEhZLWt0pKsKflC3pOXUV3JMDT64/view?usp=sharing",
>         "description": "",
>         "comment": ""
>       }
>     }
> }
> ```
> 
> I tried using `download_pretrained_model ` to download an old model, but this one doesn't seem to be compatible anymore:
> 
> ```python
> download_pretrained_model(task  ='APC', language = 'english', archive_path = '1AE2DC72vigxdAlYKjiV4_IfWsPUH7aX_')
> ```
> 
> It would be great if you could provide an English model for the new version of your package or explain how to run the examples.
> 
> Thank you 🙏
> Ingo

I just upload an English ATEPC checkpoint, you can try it.

**Comment by yangheng95** [comment]
And we call for sharing of the trained checkpoints due to the limitied computational resources. If somebody can help us, please see [here](https://github.com/yangheng95/PyABSA/blob/release/README.md#how-to-share-checkpoints-eg-checkpoints-trained-on-your-custom-dataset-with-community).

**Comment by ik4Rus** [comment]
Hi, 
thanks for the message. 
I might assist with training of new models. It would be great if you could email me (i.lange@mara.solutions). Then we could exchange which compute type is most suitable and what should be in the Dockerfile. 
Best
Ingo

**Comment by yangheng95** [comment]
> Hi,
> thanks for the message.
> I might assist with training of new models. It would be great if you could email me ([i.lange@mara.solutions](mailto:i.lange@mara.solutions)). Then we could exchange which compute type is most suitable and what should be in the Dockerfile.
> Best
> Ingo

That is great! I will email you.
