### ISSUE TITLE
Questions for evaluation

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#94]
I want to replicate results of ATEPC model from the paper A Multi-task Learning Model for Chinese-oriented Aspect Polarity Classification and Aspect Term Extraction. Specifically for the APC task. But ATEPC model gives the extracted aspects and then classify the sentiment on the extracted aspects. If the model extracts the aspects wrongly then the further classification evaluation will be hampered.

- Can you tell how did you evaluate for only APC task

- Could you share your evaluation script or any pointers how to replicate the numbers reported in the paper

**Comment by yangheng95** [comment]
In the paper, APC and ATE are evaluated separately, rather than extracting terms first. Secondly, the APC results in the paper are based on domain adapted BERT. The original LCF-ATEPC code is based on old repos (e.g., pytorch_pretrianed_bert, etc.) no longer available, but we provide a version compatible with the Transformers (https://github.com/yangheng95/LCF-ATEPC), you can try to reproduce the results (use BERT-SPC and log_step=5 is recommended).
